### ISSUE TITLE
Change token and lexer names to common community rules 

### ISSUE THREAD

**Issue by arturkasperek** [dzieje-khorinis/DaedalusCompiler#18]
<img width="299" alt="zrzut ekranu 2018-10-19 o 21 39 17" src="https://user-images.githubusercontent.com/6894763/47240103-8eb60600-d3e7-11e8-876e-d6fd47d029ee.png">

**Comment by Kisioj** [comment]
we should brainstorm about that

**Comment by Kisioj** [comment]
actually our current convention is also widely used so for now we can stay with what we have
