### ISSUE TITLE
Comment Availability

### ISSUE THREAD

**Issue by Multithread** [dzieje-khorinis/DaedalusCompiler#39]
Is it possible for you to allow Comments to be rendered out into the Tree?
I have some problems with Array-Constants and with the AI_output function.

I need to do some workaround, to work with that currently.

**Comment by arturkasperek** [comment]
What problems exactly do you have @Multithread ? We generate CSL files when you provide that param: `--gen-ou`

**Comment by Multithread** [comment]
The problem I have, is that for AI_Output, the Information about what text shall be displayed to the user, is written as comment behind the Function call. 

This information ist lost after parsing the data with the Compiler, as far as I can tell.

**Comment by arturkasperek** [comment]
@Multithread is it solved your problem ?
