### ISSUE TITLE
Reparsing (Loading, then saving) .dat files produces different binary outputs

### ISSUE THREAD

**Issue by kvdrrrrr** [dzieje-khorinis/DaedalusCompiler#49]
Using class `DatFile` from `src/DaedalusCompiler/Dat/` to load and save .dat files produces binary that differs from the original. In addition to that, it doesn't seem to work properly - the game complains about missing startup script (presumambly `STARTUP.D`).

**Comment by Kisioj** [comment]
Do you mean Gothic1 or Gothic2 `dat` file? There is random unsignificant data in `dat` files so Gothic does generate different .dat files each time. Generating .dat was tested on both: German and Polish Gothic2 scripts and our compiler gave the same results as when compiled with Gothic2.exe. Could you provide links to scripts and `dat` file generated by Gothic2?

**Comment by kvdrrrrr** [comment]
Polish version of Gothic 2's `GOTHIC.DAT` file, compiled with Gothic2.exe;  [image - symbol comparison](https://imgur.com/a/UmObxIS)

**Comment by Kisioj** [comment]
Is it `Gothic 2` or `Gothic 2 Night of the Raven`? Could you provide link to google drive where I can download your Daedalus scripts so I can test this myself?

**Comment by kvdrrrrr** [comment]
This seems to be a problem on my end - JetBrains' Rider auto-cleanup feature changed the logic of writing symbol count, after reverting back to the repo's HEAD it now works correctly.
