### ISSUE TITLE
Add Special Character support for Identifiers (e.g. @^)

### ISSUE THREAD

**Issue by Kirides** [dzieje-khorinis/DaedalusCompiler#50]
Ikarus (for example) introduces functions like `_^`, `_@`, `_@s`. Without adjustment, the compiler will fail to recognize them.

Daedalus.G4 fragment piece (newly added SpecialCharacters)
```antlr
fragment IdStart : GermanCharacter | SpecialCharacters | [a-zA-Z_];
fragment IdContinue : IdStart | Digit;
fragment GermanCharacter : [\u00DF\u00E4\u00F6\u00FC];
fragment SpecialCharacters : [@^];
```

**Comment by Kisioj** [comment]
To be honest I didn't look into what is needed for supporting Ikarus, left it for later.

@Kirides Is adding these 2 special characters everything it takes to have Ikarus support?

**Comment by Kirides** [comment]
No, there is a lot more actually...
Like method parameters named `instance`, variables named `class` and single statements like `myvar;`

I tried myself at adding support, but failed because of lack of lexer/parser knowledge.


Am 10.06.2019 00:26 schrieb Krzysztof Jura <notifications@github.com>:

To be honest I didn't look into what is needed for supporting Ikarus, left it for later.

@Kirides<https://github.com/Kirides> Is adding these 2 special characters everything it takes to have Ikarus support?

**Comment by Kirides** [comment]
Since i am now more actively developing my [vscode-daedalus](https://github.com/Kirides/vscode-daedalus) extension, i will start learning some Parser/Lexer workings to replace my current parser implementation with your compiler.

I hope i can contribute some useful additions to the community!

**Comment by Kirides** [comment]
basic ikarus and LeGo support was added in #53 which contains changes to identifiers which allow that identifiers may include `@` and `^` after the first letter
