### ISSUE TITLE
Add the path to the file or the name of the function where the compiler finds the error

### ISSUE THREAD

**Issue by N1kX94** [dzieje-khorinis/DaedalusCompiler#61]
Hello. Could you add the path to the file or the name of the function where the compiler finds the error? It would be very convenient. Using the example of GothicSourcer. I tried using Russian scripts and looking for where he found the error or something else.

**Comment by Kisioj** [comment]
@N1kX94 Thanks for this issue. Totally forgot to check syntax errors for this. If you had semantic error, it would print in which file. Should be fixed shortly.

**Comment by Kisioj** [comment]
I'm sorry it took so long, but it's finally fixed in release 0.9.0.
